name: Build PDF

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build LaTeX Document
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build PDF in container
        run: |
          docker run --rm \
            -v "$PWD:/workspace" \
            -w /workspace \
            --user root \
            texlive/texlive:latest-small \
            bash -c "
              export PATH=/usr/local/texlive/2025/bin/x86_64-linux:\$PATH && \
              apt-get update && \
              apt-get install -y --no-install-recommends python3 python3-pip make && \
              tlmgr update --self && \
              tlmgr install biber latexmk latexindent xmpincl titlesec multirow microtype csquotes biblatex biblatex-apa minted fvextra fancyvrb glossaries glossaries-english algorithmicx algorithms tocloft xstring texcount caption hyperref collection-latexextra && \
              pip3 install pygments --break-system-packages && \
              latexmk -pdf -file-line-error -halt-on-error -interaction=nonstopmode -shell-escape main.tex && \
              chmod 644 main.pdf
            "

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: thesis-pdf
          path: main.pdf
          retention-days: 30

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Download PDF
        uses: actions/download-artifact@v4
        with:
          name: thesis-pdf

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.sha }}
          name: Build ${{ github.sha }}
          files: main.pdf
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
